-- Migration 000044: DEPRECATED - Legacy $0.01 test pricing removed.
-- This migration previously set package prices to $0.01 for testing.
-- Production pricing is restored by 000052_restore_production_prices.sql.
-- Display prices are synced from Stripe via sync-display-prices-from-stripe.ts.
