-- Migration: Seed Products Data
-- Inserts initial product data from lib/products.ts

-- Insert package products (4 packages)
-- Note: IDs will be auto-generated by gen_random_uuid()
INSERT INTO products (
  slug, title, description, category, price, original_price, 
  featured, package_image, images, tagline, difficulty, duration, 
  content_hours, rating, review_count, modules, resources, bonus_assets, 
  pricing_justification
) VALUES 
-- Web Apps Package
(
  'web-apps',
  'Web Apps Package',
  'Build powerful web applications with AI assistance. Transform your skills into profitable web development projects.',
  'web-apps',
  1997.00,
  2997.00,
  true,
  '/package-2.png',
  '["/package-2.png"]'::jsonb,
  'Convert powerful AI solutions into profitable web applications that generate USD revenue',
  'intermediate',
  'Self-paced',
  '40+ hours',
  4.8,
  127,
  '[
    {
      "title": "AI-Powered Development Fundamentals",
      "description": "Master the fundamentals of building web apps with AI assistance",
      "hours": "6-8 hours",
      "items": [
        "Building web apps with AI assistance (ChatGPT, GitHub Copilot, Cursor)",
        "AI-powered debugging and code optimization",
        "Prompt engineering for development tasks"
      ]
    },
    {
      "title": "Full-Stack Web Application Course",
      "description": "Complete guide to building full-stack applications",
      "hours": "15-20 hours",
      "items": [
        "Modern frameworks (Next.js, React, Node.js) with AI enhancement",
        "Database integration with AI-assisted schema design",
        "API development and integration strategies"
      ]
    },
    {
      "title": "AI Integration Mastery",
      "description": "Learn to integrate AI APIs and build custom AI features",
      "hours": "8-10 hours",
      "items": [
        "Integrating AI APIs (OpenAI, Anthropic, etc.)",
        "Building custom AI features (chatbots, recommendation systems)",
        "Real-time AI processing and optimization"
      ]
    },
    {
      "title": "Deployment & Scaling",
      "description": "Deploy and scale your applications effectively",
      "hours": "5-6 hours",
      "items": [
        "CI/CD with AI assistance",
        "Performance optimization",
        "Security best practices"
      ]
    }
  ]'::jsonb,
  '[
    {
      "category": "Code Templates",
      "items": [
        "20+ production-ready code templates",
        "15+ starter project templates",
        "AI prompt library (200+ developer prompts)"
      ]
    },
    {
      "category": "Deployment Guides",
      "items": [
        "Deployment guides for Vercel, AWS, etc.",
        "Database templates and schemas"
      ]
    },
    {
      "category": "Business Resources",
      "items": [
        "Pricing strategies guide",
        "Client acquisition templates",
        "Proposal templates",
        "Contract templates",
        "Portfolio optimization guide"
      ]
    }
  ]'::jsonb,
  '["Access to private Discord community", "Monthly Q&A sessions (6 months)", "Code review sessions", "Lifetime updates", "Certificate of completion"]'::jsonb,
  'Comprehensive full-stack development course with production-ready templates and resources. Comparable to bootcamps priced at $2,000-$6,000+. Total content: 40+ hours of structured learning with immediate ROI through templates and tools.'
),
-- Social Media Package
(
  'social-media',
  'Social Media Package',
  'Monetize your AI-driven content by creating profitable social media automation tools. Grow your presence and engagement.',
  'social-media',
  997.00,
  1497.00,
  true,
  '/package-1.png',
  '["/package-1.png"]'::jsonb,
  'Monetize your AI-driven content by creating profitable social media automation tools',
  'beginner',
  'Self-paced',
  '30+ hours',
  4.9,
  203,
  '[
    {
      "title": "AI Content Creation Mastery",
      "description": "Master creating engaging content with AI tools",
      "hours": "8-10 hours",
      "items": [
        "Writing engaging copy with AI",
        "Image/video generation workflows",
        "Brand voice consistency with AI tools"
      ]
    },
    {
      "title": "Multi-Platform Strategy",
      "description": "Develop strategies for all major social platforms",
      "hours": "10-12 hours",
      "items": [
        "Platform-specific strategies (Instagram, TikTok, LinkedIn, Twitter)",
        "Content calendars and automation",
        "Algorithm optimization"
      ]
    },
    {
      "title": "Growth & Engagement Systems",
      "description": "Build systems for sustainable growth",
      "hours": "6-8 hours",
      "items": [
        "AI-powered audience analysis",
        "Engagement optimization",
        "Community management automation"
      ]
    },
    {
      "title": "Monetization & Analytics",
      "description": "Turn your social media into a revenue stream",
      "hours": "5-6 hours",
      "items": [
        "Influencer partnerships",
        "Affiliate marketing with AI",
        "Analytics and ROI tracking"
      ]
    }
  ]'::jsonb,
  '[
    {
      "category": "Content Templates",
      "items": [
        "500+ AI-generated content templates",
        "50+ ready-to-use caption templates",
        "30-day content calendar templates",
        "Brand voice guides (multiple industries)",
        "Hashtag research tools and databases",
        "Analytics dashboard templates"
      ]
    },
    {
      "category": "Automation Tools",
      "items": [
        "Social media automation workflows",
        "Content scheduling setups",
        "Engagement bot configurations",
        "AI prompt library (300+ social media prompts)"
      ]
    },
    {
      "category": "Business Assets",
      "items": [
        "Pricing guide for social media services",
        "Client onboarding templates",
        "Reporting templates",
        "Service package templates"
      ]
    }
  ]'::jsonb,
  '["Private community access", "Monthly strategy sessions (6 months)", "Content feedback sessions", "Trend alerts and updates", "Lifetime access to updates"]'::jsonb,
  'Complete social media mastery with 500+ templates and automation systems. Comparable to agency services at $500-$2,000/month. Total content: 30+ hours of video training with immediate value through templates and automation setups that save 10+ hours/week.'
),
-- Agency Package
(
  'agency',
  'Agency Package',
  'Build a profitable agency selling AI-powered services to business clients. Scale your operations with proven systems.',
  'agency',
  2997.00,
  4497.00,
  true,
  '/package-3.png',
  '["/package-3.png"]'::jsonb,
  'Build a profitable agency selling AI-powered services to business clients',
  'intermediate',
  'Self-paced',
  '40+ hours',
  4.7,
  89,
  '[
    {
      "title": "Agency Foundation & Systems",
      "description": "Build a solid foundation for your agency",
      "hours": "8-10 hours",
      "items": [
        "Agency business models",
        "Pricing and service packages",
        "Operations and workflows"
      ]
    },
    {
      "title": "AI-Powered Service Delivery",
      "description": "Deliver exceptional services using AI tools",
      "hours": "12-15 hours",
      "items": [
        "AI tools for each service (SEO, content, ads, web dev)",
        "Scalable service delivery systems",
        "Quality control with AI assistance"
      ]
    },
    {
      "title": "Client Acquisition & Retention",
      "description": "Build a pipeline of high-value clients",
      "hours": "8-10 hours",
      "items": [
        "AI-powered lead generation",
        "Sales processes and proposals",
        "Client onboarding and retention"
      ]
    },
    {
      "title": "Scaling & Team Management",
      "description": "Scale your agency operations effectively",
      "hours": "6-8 hours",
      "items": [
        "Hiring and training with AI",
        "Standard operating procedures",
        "Scaling operations"
      ]
    },
    {
      "title": "Financial Management",
      "description": "Optimize your agency''s financial performance",
      "hours": "4-5 hours",
      "items": [
        "Pricing strategies",
        "Profit optimization",
        "Financial tracking and forecasting"
      ]
    }
  ]'::jsonb,
  '[
    {
      "category": "Business Resources",
      "items": [
        "Complete agency SOP library (50+ documents)",
        "Service package templates (20+ variations)",
        "Proposal templates ($10K-$100K+ projects)",
        "Contract templates",
        "Onboarding system templates",
        "Client reporting templates (monthly/quarterly)"
      ]
    },
    {
      "category": "Operational Tools",
      "items": [
        "AI workflow automations",
        "Client management system setup",
        "Project management templates",
        "Team training materials",
        "Quality assurance checklists"
      ]
    },
    {
      "category": "Sales & Marketing",
      "items": [
        "Sales script library",
        "Email sequences (cold outreach, follow-ups)",
        "Case study templates",
        "Testimonial collection systems",
        "Pricing calculator tools"
      ]
    }
  ]'::jsonb,
  '["Private mastermind community", "Monthly group coaching calls (12 months)", "1-on-1 strategy session", "Access to agency case studies", "Legal document templates", "Lifetime updates and new content"]'::jsonb,
  'Complete agency scaling system with comprehensive SOP library and templates. Comparable to agency coaching programs at $2,000-$10,000+. Total content: 40+ hours of training with immediate implementation through templates. ROI potential: $10K-$50K+ monthly revenue increase.'
),
-- Freelancing Package
(
  'freelancing',
  'Freelancing Package',
  'Offer your AI expertise as a freelancer to turn automated solutions into USD earnings. Build a successful freelancing career.',
  'freelancing',
  497.00,
  797.00,
  true,
  '/package-4.png',
  '["/package-4.png"]'::jsonb,
  'Offer your AI expertise as a freelancer to turn automated solutions into USD earnings',
  'beginner',
  'Self-paced',
  '35+ hours',
  4.6,
  156,
  '[
    {
      "title": "Freelancing Fundamentals",
      "description": "Start your freelancing journey on the right foot",
      "hours": "6-8 hours",
      "items": [
        "Starting and positioning",
        "Niche selection with AI insights",
        "Portfolio development"
      ]
    },
    {
      "title": "AI Tools for Freelancers",
      "description": "Leverage AI to boost productivity and quality",
      "hours": "10-12 hours",
      "items": [
        "Productivity tools (ChatGPT, Claude, etc.)",
        "Project management automation",
        "Time tracking and optimization"
      ]
    },
    {
      "title": "Client Acquisition Systems",
      "description": "Build systems to attract high-paying clients",
      "hours": "8-10 hours",
      "items": [
        "AI-powered outreach",
        "Proposal writing with AI",
        "Negotiation strategies",
        "Building referral systems"
      ]
    },
    {
      "title": "Service Delivery & Quality",
      "description": "Deliver exceptional work efficiently",
      "hours": "6-8 hours",
      "items": [
        "Delivering high-quality work efficiently",
        "Client communication automation",
        "Project management workflows"
      ]
    },
    {
      "title": "Pricing & Financial Growth",
      "description": "Price your services for maximum income",
      "hours": "5-6 hours",
      "items": [
        "Pricing strategies ($50-$500+/hour)",
        "Contract negotiation",
        "Financial management",
        "Scaling from freelancer to agency"
      ]
    }
  ]'::jsonb,
  '[
    {
      "category": "Business Templates",
      "items": [
        "100+ proposal templates (various services)",
        "50+ contract templates",
        "Invoice templates and systems",
        "Client onboarding templates",
        "Portfolio website templates",
        "Email template library (100+ templates)"
      ]
    },
    {
      "category": "Business Tools",
      "items": [
        "Rate calculator tool",
        "Project scope template library",
        "Client questionnaire templates",
        "Time tracking setups",
        "Automated follow-up sequences"
      ]
    },
    {
      "category": "Industry Guides",
      "items": [
        "Writing/Content creation",
        "Web development",
        "Design",
        "Marketing",
        "Consulting"
      ]
    }
  ]'::jsonb,
  '["Private freelancer community", "Monthly group calls (6 months)", "Q&A sessions", "Job board access", "Lifetime updates", "Certificate of completion"]'::jsonb,
  'Complete freelancer business toolkit with comprehensive templates and guides. Total content: 35+ hours of training with immediate value through templates. ROI potential: $1K-$10K+ monthly income increase. Accessible pricing for individual freelancers with can pay for itself with 1-2 projects.'
)
ON CONFLICT (id) DO NOTHING;

-- Insert sample products (12 products)
INSERT INTO products (
  slug, title, description, category, price, original_price, 
  featured, difficulty, duration
) VALUES 
('ai-ecommerce-builder', 'AI-Powered E-Commerce Builder', 'Create stunning online stores with AI-assisted design and automation', 'web-apps', 299.00, 499.00, true, 'beginner', '6 weeks'),
('social-content-generator', 'Social Media Content Generator', 'Generate engaging posts, captions, and content calendars automatically', 'social-media', 149.00, 249.00, true, 'beginner', '4 weeks'),
('client-management-system', 'Client Management System', 'Streamline your agency workflow with AI-powered project management', 'agency', 399.00, 599.00, true, 'intermediate', '8 weeks'),
('freelancer-portfolio', 'Freelancer Portfolio Platform', 'Build a professional portfolio that attracts high-paying clients', 'freelancing', 199.00, 349.00, true, 'beginner', '3 weeks'),
('saas-dashboard-template', 'SaaS Dashboard Template', 'Modern dashboard template with AI analytics and reporting', 'web-apps', 249.00, NULL, false, 'intermediate', '5 weeks'),
('instagram-automation', 'Instagram Growth Automation', 'Automate engagement and grow your Instagram following organically', 'social-media', 179.00, NULL, false, 'beginner', '4 weeks'),
('agency-proposal-generator', 'Agency Proposal Generator', 'Create winning proposals in minutes with AI-powered templates', 'agency', 279.00, NULL, false, 'beginner', '2 weeks'),
('freelance-invoice-system', 'Freelance Invoice System', 'Professional invoicing and payment tracking for freelancers', 'freelancing', 129.00, NULL, false, 'beginner', '2 weeks'),
('api-integration-platform', 'API Integration Platform', 'Connect multiple services with AI-powered API integrations', 'web-apps', 349.00, NULL, false, 'advanced', '10 weeks'),
('tiktok-strategy', 'TikTok Content Strategy', 'Viral content strategies and AI-powered trend analysis', 'social-media', 199.00, NULL, false, 'intermediate', '6 weeks'),
('team-collaboration-tool', 'Team Collaboration Tool', 'AI-enhanced collaboration platform for distributed teams', 'agency', 449.00, NULL, false, 'intermediate', '9 weeks'),
('client-communication-system', 'Client Communication System', 'Automate client updates and maintain professional communication', 'freelancing', 159.00, NULL, false, 'beginner', '3 weeks')
ON CONFLICT (slug) DO NOTHING;

